/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_chxemay.Form;
import java.beans.PropertyVetoException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ql_chxemay.ConnectionSQLServer;
import ql_chxemay.DAO.DAO_HoaDon;
import ql_chxemay.DAO.DAO_TaiKhoanTruyCap;
import ql_chxemay.POJO.Pojo_TaiKhoan;

/**
 *
 * @author Ngo Truong An
 */
public class DoiMatKhau extends javax.swing.JInternalFrame {

    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passMKCu = new javax.swing.JPasswordField();
        passMKMoi = new javax.swing.JPasswordField();
        passXacNhanMKMoi = new javax.swing.JPasswordField();
        btnLuuMKMoi = new javax.swing.JButton();
        checkHienMatKhau = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Đổi Mật Khẩu");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modify-key-icon.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("THAY ĐỔI MẬT KHẨU");

        jLabel2.setText("Nhập Mật Khẩu Cũ:");

        jLabel3.setText("Nhập Mật Khẩu Mới:");

        jLabel4.setText("Xác Nhận Mật Khẩu Mới:");

        btnLuuMKMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/floppy-icon.png"))); // NOI18N
        btnLuuMKMoi.setText("Lưu Thay Đổi");
        btnLuuMKMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuMKMoiActionPerformed(evt);
            }
        });

        checkHienMatKhau.setText("Hiện mật khẩu");
        checkHienMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHienMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkHienMatKhau)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passXacNhanMKMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(passMKMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(passMKCu)
                            .addComponent(btnLuuMKMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passXacNhanMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkHienMatKhau)
                .addGap(34, 34, 34)
                .addComponent(btnLuuMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuMKMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuMKMoiActionPerformed
        // TODO add your handling code here:
        if(passMKCu.getText().trim().isEmpty()|| passMKMoi.getText().trim().isEmpty()|| passXacNhanMKMoi.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Mật Khẩu không được để trống. Vui lòng điền đầy đủ thông tin!","Lưu ý",1);

        }
        else {
            Pojo_TaiKhoan x=DAO_TaiKhoanTruyCap.taikhoantruycap;
            if(passMKCu.getText().trim().equals(x.getMatkhau())==false)
            {
                JOptionPane.showMessageDialog(this,"Mật Khẩu cũ không khớp. Vui lòng kiểm tra lại!","Lưu ý",2);
            }
            else
            ///Kết nối với tài khoản bên SQL database
            {
                if(passMKMoi.getText().trim().equals(passXacNhanMKMoi.getText().trim())==false)
                {
                    JOptionPane.showMessageDialog(this,"Mật Khẩu xác nhận không đúng. Vui lòng kiểm tra lại!","Lưu ý",2);

                }
                else
                {
                    ConnectionSQLServer c=new ConnectionSQLServer();
                    try {
                        c.OpenConnection();
                        String sqlCheck="UPDATE TAIKHOAN SET MATKHAU=? WHERE TENDANGNHAP=?";
                        PreparedStatement ps=c.getCon().prepareStatement(sqlCheck);
                        ps.setString(1,passXacNhanMKMoi.getText().trim());
                        ps.setString(2,x.getTendn());
                        int numberRowsAffected=ps.executeUpdate();
                        c.CloseConnection();
                        JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                        this.hide();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnLuuMKMoiActionPerformed

    private void checkHienMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHienMatKhauActionPerformed
        // TODO add your handling code here:
         if(checkHienMatKhau.isSelected())
        {
            passMKCu.setEchoChar((char)0);
            passMKMoi.setEchoChar((char)0);
            passXacNhanMKMoi.setEchoChar((char)0);
        }
    }//GEN-LAST:event_checkHienMatKhauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuMKMoi;
    private javax.swing.JCheckBox checkHienMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passMKCu;
    private javax.swing.JPasswordField passMKMoi;
    private javax.swing.JPasswordField passXacNhanMKMoi;
    // End of variables declaration//GEN-END:variables
}
