/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_chxemay.Form;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import ql_chxemay.DAO.DAO_TaiKhoanTruyCap;

/**
 *
 * @author Ngo Truong An
 */
public class Fr_Main extends javax.swing.JFrame {

    /**
     * Creates new form Fr_Main
     */
    BanHang banhang;
    KiemKho kiemkho;
    QuanLi quanli;
    ThongKe thongke;
    ThongTinNguoiDung ttnd;
    DoiMatKhau doimatkhau;
    public Fr_Main() {
        initComponents();
        if(DAO_TaiKhoanTruyCap.taikhoantruycap.getMachucvu().trim().equals("BH"))
        {
            menuKiemKho.setEnabled(false);
            menuQuanLi.setEnabled(false);
        }
        else if(DAO_TaiKhoanTruyCap.taikhoantruycap.getMachucvu().trim().equals("KK"))
        {
            menuBanHang.setEnabled(false);
            menuQuanLi.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        DesktopMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHeThong = new javax.swing.JMenu();
        menuTaiKhoan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuDangXuat = new javax.swing.JMenuItem();
        menuNghiepVu = new javax.swing.JMenu();
        menuBanHang = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuKiemKho = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuQuanLi = new javax.swing.JMenuItem();
        menuCN = new javax.swing.JMenu();
        menuThongKe = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DesktopMainLayout = new javax.swing.GroupLayout(DesktopMain);
        DesktopMain.setLayout(DesktopMainLayout);
        DesktopMainLayout.setHorizontalGroup(
            DesktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1043, Short.MAX_VALUE)
        );
        DesktopMainLayout.setVerticalGroup(
            DesktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );

        menuHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/system-icon.png"))); // NOI18N
        menuHeThong.setText("Hệ Thống");

        menuTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user-info-icon.png"))); // NOI18N
        menuTaiKhoan.setText("Tài Khoản");
        menuTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTaiKhoanActionPerformed(evt);
            }
        });
        menuHeThong.add(menuTaiKhoan);
        menuHeThong.add(jSeparator1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modify-key-icon.png"))); // NOI18N
        jMenuItem4.setText("Đổi Mật Khẩu");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuHeThong.add(jMenuItem4);
        menuHeThong.add(jSeparator5);

        menuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logout-icon.png"))); // NOI18N
        menuDangXuat.setText("Đăng Xuất");
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        menuHeThong.add(menuDangXuat);

        jMenuBar1.add(menuHeThong);

        menuNghiepVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user-group-icon.png"))); // NOI18N
        menuNghiepVu.setText("Nghiệp Vụ");

        menuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carts.png"))); // NOI18N
        menuBanHang.setText("Bán Hàng");
        menuBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBanHangActionPerformed(evt);
            }
        });
        menuNghiepVu.add(menuBanHang);
        menuNghiepVu.add(jSeparator2);

        menuKiemKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/store.png"))); // NOI18N
        menuKiemKho.setText("Kiểm Kho");
        menuKiemKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKiemKhoActionPerformed(evt);
            }
        });
        menuNghiepVu.add(menuKiemKho);
        menuNghiepVu.add(jSeparator3);

        menuQuanLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/manager.png"))); // NOI18N
        menuQuanLi.setText("Quản Lí");
        menuQuanLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLiActionPerformed(evt);
            }
        });
        menuNghiepVu.add(menuQuanLi);

        jMenuBar1.add(menuNghiepVu);

        menuCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tool-box-icon.png"))); // NOI18N
        menuCN.setText("Chức Năng");

        menuThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tools-2-icon.png"))); // NOI18N
        menuThongKe.setText("Thống Kê");
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });
        menuCN.add(menuThongKe);

        jMenuBar1.add(menuCN);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed
        // TODO add your handling code here:
        Fr_DangNhap f = new Fr_DangNhap();
        f.setLocationRelativeTo(null); //đưa form ra giữa màn hình
        f.setVisible(true);
        this.hide();
    }//GEN-LAST:event_menuDangXuatActionPerformed

    private void menuKiemKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKiemKhoActionPerformed
        // TODO add your handling code here:
         if(kiemkho==null||kiemkho.isClosed())
        {
            kiemkho=new KiemKho();
            DesktopMain.add(kiemkho).setVisible(true);
        }
        else
            
            try {
                kiemkho.setSelected(true);
         } catch (PropertyVetoException ex) {
             Logger.getLogger(Fr_Main.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_menuKiemKhoActionPerformed

    private void menuBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBanHangActionPerformed
        // TODO add your handling code here:
         if(banhang==null||banhang.isClosed())
        {
            banhang=new BanHang();
            DesktopMain.add(banhang).setVisible(true);
        }
        else
            
            try {
                banhang.setSelected(true);
         } catch (PropertyVetoException ex) {
             Logger.getLogger(Fr_Main.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_menuBanHangActionPerformed

    private void menuQuanLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLiActionPerformed
        // TODO add your handling code here:
        if(quanli==null||quanli.isClosed())
        {
            quanli=new QuanLi();
            DesktopMain.add(quanli).setVisible(true);
        }
        else
            try {
                quanli.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Fr_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuQuanLiActionPerformed

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
        if(thongke==null||thongke.isClosed())
        {
            thongke=new ThongKe();
            DesktopMain.add(thongke).setVisible(true);
        }
        else
            try {
                thongke.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Fr_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuThongKeActionPerformed

    private void menuTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTaiKhoanActionPerformed
        // TODO add your handling code here:
        if(ttnd==null||ttnd.isClosed())
        {
            ttnd=new ThongTinNguoiDung();
            DesktopMain.add(ttnd).setVisible(true);
        }
        else
            try {
                ttnd.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Fr_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuTaiKhoanActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if(doimatkhau==null||doimatkhau.isClosed())
        {
            doimatkhau=new DoiMatKhau();
            DesktopMain.add(doimatkhau).setVisible(true);
        }
        else
            try {
                doimatkhau.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Fr_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fr_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fr_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fr_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fr_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fr_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem menuBanHang;
    private javax.swing.JMenu menuCN;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenu menuHeThong;
    private javax.swing.JMenuItem menuKiemKho;
    private javax.swing.JMenu menuNghiepVu;
    private javax.swing.JMenuItem menuQuanLi;
    private javax.swing.JMenuItem menuTaiKhoan;
    private javax.swing.JMenuItem menuThongKe;
    // End of variables declaration//GEN-END:variables
}
