/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_chxemay.Form;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import ql_chxemay.DAO.DAO_CTHDN;
import ql_chxemay.DAO.DAO_HoaDonNhap;
import ql_chxemay.DAO.DAO_NCC;
import ql_chxemay.DAO.DAO_NhanVien;
import ql_chxemay.DAO.DAO_TaiKhoanTruyCap;
import ql_chxemay.DAO.DAO_XeMay;
import ql_chxemay.POJO.Pojo_CTHD;
import ql_chxemay.POJO.Pojo_CTHDN;
import ql_chxemay.POJO.Pojo_HoaDon;
import ql_chxemay.POJO.Pojo_HoaDonNhap;
import ql_chxemay.DAO.DAO_LoaiXe;
import ql_chxemay.DAO.DAO_NhaSanXuat;
import ql_chxemay.POJO.Pojo_XeMay;


/**
 *
 * @author Ngo Truong An
 */
public class KiemKho extends javax.swing.JInternalFrame {

    /**
     * Creates new form IJFr_KiemKho
     */
    Vector data_NV =new Vector();
    DAO_NhanVien dao_NV=new DAO_NhanVien();
    DAO_XeMay dao_XM=new DAO_XeMay();
    Vector header_XM =new Vector();
    Vector data_XM =new Vector();
    DAO_CTHDN dao_CTHDN=new DAO_CTHDN();
    Vector data_CTHDN=new Vector();
    Vector header_CTHDN=new Vector();
    DAO_HoaDonNhap dao_HDN=new DAO_HoaDonNhap();
    DAO_HoaDonNhap dao_LSN=new DAO_HoaDonNhap();
    Vector header_LSN =new Vector();
    Vector data_LSN =new Vector();
    DAO_NCC dao_NCC=new DAO_NCC();
    DAO_NhaSanXuat dao_NSX=new DAO_NhaSanXuat();
    Vector data_NSX=new Vector();
    Vector data_NCC=new Vector();
     Vector data_HDN=new Vector();
     DAO_LoaiXe dao_LoaiXe=new DAO_LoaiXe();
     Vector data_ML=new Vector();
   
   
    public KiemKho() {
        initComponents();
        loadComboBox();
        loadComboBoxMaNCC();
        loadComboBoxMaXe();
        loadComboBoxMaNSX();
        loadComboBoxNSX();
        loadComboBoxMaNCCTabKhoXe();
        AutoCompleteDecorator.decorate(cbMaXe);
        loadComboBoxMaLoaiTabKho();
        loadDataTabKhoXe();
        loadThongTinLSN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSoHDN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbMaNV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTongNhap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        cbMaNCC = new javax.swing.JComboBox<>();
        btnHoaDonNhapMoi = new javax.swing.JButton();
        btnLuuHD = new javax.swing.JButton();
        btnHuyHD = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        IDCTHDN = new javax.swing.JTextField();
        txtSLN = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbMaXe = new javax.swing.JComboBox<>();
        btnThemCTHDN = new javax.swing.JButton();
        btnXoaCTHDN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCTHDN = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaXeTabKhoXe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTenXeTabKhoXe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhienBanTabKhoXe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMauXeTabKhoXe = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNSXTabKhoXe = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNCCTabKhoXe = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtGiaBanTabKhoXe = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtBaoHanhTabKhoXe = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTonKhoTabKhoXe = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        cbMaLoaiTabKhoXe = new javax.swing.JComboBox<>();
        cbMaNSX = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        btnXoaXe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableXeMay = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        cbTenNSX = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        btnTatCa = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtSoHDLSN = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtNgayNhapLSN = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtMaNCCLSN = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtSoXeNhapLSN = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtTongTienLSN = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtTrangThaiLSN = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtGhiChuLSN = new javax.swing.JTextField();
        txtMaNVLSN = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnXemCTHDN = new javax.swing.JButton();
        btnHuyHDN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLSHDN = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableLSCTHDN = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Kiểm Kho");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/store (1).png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn Nhập:"));

        jLabel2.setText("Số Hóa Đơn:");

        jLabel3.setText("Ngày Nhập:");

        jLabel4.setText("Nhân Viên:");

        jLabel5.setText("Mã NCC:");

        jLabel6.setText("Tổng Số Xe:");

        jLabel7.setText("Tổng Tiền:");

        jLabel8.setText("Trạng Thái:");

        jLabel9.setText("Ghi Chú:");

        cbMaNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(37, 37, 37)
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoHDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5))
                    .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtTongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        btnHoaDonNhapMoi.setText(" Mới");
        btnHoaDonNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonNhapMoiActionPerformed(evt);
            }
        });

        btnLuuHD.setText("Lưu");
        btnLuuHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHDActionPerformed(evt);
            }
        });

        btnHuyHD.setText("Hủy Hóa Đơn");
        btnHuyHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHDActionPerformed(evt);
            }
        });

        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel20.setText("ID:");

        jLabel21.setText("Mã Xe:");

        jLabel22.setText("Số Lượng:");

        jLabel23.setText("Giá Nhập:");

        cbMaXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnThemCTHDN.setText("Thêm");
        btnThemCTHDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTHDNActionPerformed(evt);
            }
        });

        btnXoaCTHDN.setText("Xóa");
        btnXoaCTHDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTHDNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDCTHDN)
                            .addComponent(cbMaXe, 0, 95, Short.MAX_VALUE)))
                    .addComponent(txtSLN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaCTHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemCTHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDCTHDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemCTHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtSLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnXoaCTHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(cbMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel22)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel23)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tableCTHDN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableCTHDN);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHoaDonNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(btnHuyHD, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLuuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHoaDonNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHuyHD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(btnLuuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhập Kho", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Xe"));

        jLabel1.setText("Mã Xe:");

        jLabel10.setText("Tên Xe:");

        jLabel11.setText("Phiên Bản:");

        jLabel12.setText("Màu Xe:");

        jLabel13.setText("Mã Loại:");

        jLabel14.setText("NSX:");

        jLabel15.setText("NCC:");

        jLabel16.setText("Giá Bán:");

        jLabel17.setText("Bảo Hành:");

        jLabel18.setText("Số Lượng:");

        btnTim.setText("Tìm ");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/floppy-icon.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-file-icon (1).png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-validated-icon (1).png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        cbMaLoaiTabKhoXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cbMaNSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel33.setText("(**)");

        btnXoaXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-validated-icon (1).png"))); // NOI18N
        btnXoaXe.setText("Xóa");
        btnXoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaXeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaXeTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenXeTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhienBanTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMauXeTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cbMaLoaiTabKhoXe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(187, 187, 187)))
                                .addGap(2, 2, 2)
                                .addComponent(jLabel33)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnTim)
                                .addGap(79, 79, 79)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txtTonKhoTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNSXTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNCCTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaBanTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBaoHanhTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMaNSX, 0, 60, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaXeTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(9, 9, 9)
                        .addComponent(txtTenXeTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhienBanTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMauXeTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txtNSXTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNCCTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbMaNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(txtGiaBanTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBaoHanhTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel13))
                            .addComponent(cbMaLoaiTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTonKhoTabKhoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableXeMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableXeMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableXeMayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableXeMay);

        jLabel34.setText("Nhà Sản Xuất:");

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        btnTatCa.setText("Tất Cả");
        btnTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatCaActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel53.setText("DANH SÁCH THÔNG TIN XE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(cbTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoc)
                .addGap(34, 34, 34)
                .addComponent(btnTatCa)
                .addGap(609, 609, 609))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel53)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel53)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cbTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoc)
                    .addComponent(btnTatCa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kho Xe", jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn Nhập:"));

        jLabel25.setText("Số Hóa Đơn:");

        jLabel26.setText("Ngày Nhập:");

        jLabel27.setText("Nhân Viên:");

        jLabel28.setText("Mã NCC:");

        jLabel29.setText("Số Xe Nhập:");

        jLabel30.setText("Tổng Tiền:");

        jLabel31.setText("Trạng Thái:");

        jLabel32.setText("Ghi Chú:");

        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnXemCTHDN.setText("Chi Tiết");
        btnXemCTHDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemCTHDNActionPerformed(evt);
            }
        });

        btnHuyHDN.setText("Hủy HĐ");
        btnHuyHDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHDNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(txtSoHDLSN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNCCLSN)
                            .addComponent(txtMaNVLSN)
                            .addComponent(txtNgayNhapLSN))))
                .addGap(75, 75, 75)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel30)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnXemCTHDN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHuyHDN))
                    .addComponent(txtGhiChuLSN, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtSoXeNhapLSN)
                    .addComponent(txtTongTienLSN)
                    .addComponent(txtTrangThaiLSN))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel25))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoHDLSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTimKiem))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNVLSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(txtTongTienLSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtNgayNhapLSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(txtTrangThaiLSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtMaNCCLSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(txtGhiChuLSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoXeNhapLSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemCTHDN)
                    .addComponent(btnHuyHDN))
                .addContainerGap())
        );

        tableLSHDN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableLSHDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLSHDNMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableLSHDN);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("HOÁ ĐƠN NHẬP");

        tableLSCTHDN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableLSCTHDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLSCTHDNMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableLSCTHDN);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("CHI TIẾT HÓA ĐƠN NHẬP");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(290, 290, 290))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lịch Sử Nhập", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void loadComboBox()
    {

        dao_NV.loadDataKiemKho(data_NV);
        for(int i=0;i<data_NV.size();i++)
        {
            Vector v=(Vector)data_NV.get(i);
            String item=v.get(0).toString();
            cbMaNV.addItem(item);
        }
        cbMaNV.setSelectedIndex(0);
        
    }
       public void loadComboBoxNSX()
    {
        dao_NSX.loadData(data_NSX);
        for(int i=0;i<data_NSX.size();i++)
        {
            Vector v=(Vector)data_NSX.get(i);
            String item=v.get(1).toString();
            cbTenNSX.addItem(item);
        }
        cbTenNSX.setSelectedIndex(-1);
    }
     public void loadComboBoxMaNCC()
    {
        dao_NCC.loadData(data_NCC);
        for(int i=0;i<data_NCC.size();i++)
        {
            Vector v=(Vector)data_NCC.get(i);
            String item=v.get(0).toString();
            cbMaNCC.addItem(item);
        }
        cbMaNCC.setSelectedIndex(-1);
    }
     public void loadComboBoxMaNSX()
    {
        dao_NSX.loadData(data_NSX);
        for(int i=0;i<data_NSX.size();i++)
        {
            Vector v=(Vector)data_NSX.get(i);
            String item=v.get(0).toString();
            cbMaNSX.addItem(item);
        }
        cbMaNSX.setSelectedIndex(-1);
    }
     public void loadComboBoxMaNCCTabKhoXe()
    {
        dao_NCC.loadData(data_NCC);
        for(int i=0;i<data_NCC.size();i++)
        {
            Vector v=(Vector)data_NCC.get(i);
            String item=v.get(0).toString();
            jComboBox1.addItem(item);
        }
        jComboBox1.setSelectedIndex(-1);
    }
    public void loadComboBoxMaXe()
    {
        dao_XM.loadData(data_XM);
        for(int i=0;i<data_XM.size();i++)
        {
            Vector v=(Vector)data_XM.get(i);
            String item=v.get(0).toString();
            cbMaXe.addItem(item);
        }
        cbMaXe.setSelectedIndex(-1);
    }
    public void loadComboBoxMaLoaiTabKho()
    {
        dao_LoaiXe.loadData(data_ML);
        for(int i=0;i<data_ML.size();i++)
        {
            Vector v=(Vector)data_ML.get(i);
            String item=v.get(0).toString();
            cbMaLoaiTabKhoXe.addItem(item);
        }
        cbMaLoaiTabKhoXe.setSelectedIndex(-1);
    }
    public void loadDataTabKhoXe()
{
        header_XM.removeAllElements();
        header_XM.add("Mã Xe");
        header_XM.add("Tên Xe");
        header_XM.add("Phiên Bản");
        header_XM.add("Màu Xe");
        header_XM.add("Mã Loại");
        header_XM.add("Mã NSX");
        header_XM.add("Mã NCC");
        header_XM.add("Giá Bán");
        header_XM.add("BH");
        header_XM.add("Số Lượng");
         header_XM.add("Tình Trạng");
        dao_XM.loadData(data_XM);
        tableXeMay.setModel(new DefaultTableModel(data_XM,header_XM));
}
public void loadThongTinLSN()
{
   header_LSN.removeAllElements();
   header_LSN.add("Số HD");
   header_LSN.add("Mã NV:");
   header_LSN.add("Ngày Nhập");
   header_LSN.add("Mã NCC");
   header_LSN.add("Tổng Nhập");
   header_LSN.add("Tổng Tiền");
   header_LSN.add("Tình Trạng");
   header_LSN.add("Ghi Chú");
   dao_HDN.loadData(data_LSN);
   tableLSHDN.setModel(new DefaultTableModel(data_LSN, header_LSN));
}
public void layDuLieuCTHDN(int sohd)
   {

       header_CTHDN.removeAllElements();
       header_CTHDN.add("SOHD");
       header_CTHDN.add("ID");
       header_CTHDN.add("MAXE");
       header_CTHDN.add("SOLUONG");
       header_CTHDN.add("DONGIA");
       header_CTHDN.add("THANHTIEN");
       dao_CTHDN.loadData(data_CTHDN,sohd);
       tableCTHDN.setModel(new DefaultTableModel(data_CTHDN, header_CTHDN));
   }
    private void btnHoaDonNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonNhapMoiActionPerformed
        // TODO add your handling code here:
        getText();
        dao_HDN.loadData(data_HDN);
        int sohd=dao_HDN.getLast();
        sohd++;
        txtSoHDN.setText(String.format("%d", sohd));
    }//GEN-LAST:event_btnHoaDonNhapMoiActionPerformed

    private void btnLuuHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHDActionPerformed
        // TODO add your handling code here:

        if(txtTrangThai.getText().equals("ĐÃ THANH TOÁN"))
        {
             JOptionPane.showMessageDialog(this,"Hóa đơn đã thanh toán. Vui lòng tạo hóa đơn mới!","Lưu ý",1);
        }
        if(txtSoHDN.getText().trim().equals("")||cbMaNCC.getSelectedItem()==null)
        {
            JOptionPane.showMessageDialog(this,"Chưa đủ thông tin. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else
        {
            Pojo_HoaDonNhap x=new Pojo_HoaDonNhap(Integer.parseInt(txtSoHDN.getText().trim()),cbMaNV.getSelectedItem().toString(), cbMaNCC.getSelectedItem().toString().trim());
            dao_HDN.add(x);
            Pojo_HoaDonNhap hd=dao_HDN.search(x.getMahdn());
            setText(hd);
            int id=dao_CTHDN.getLast(hd);
            id++;
            IDCTHDN.setText(String.format("%d",id));
        }
    }//GEN-LAST:event_btnLuuHDActionPerformed

    private void btnHuyHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHDActionPerformed
        // TODO add your handling code here:
        if(txtSoHDN.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không có hóa đơn nào để hủy!","Thông báo",1);
        }
        else
        {
            int sohd=Integer.parseInt(txtSoHDN.getText());
            if(dao_HDN.search(sohd)==null)
            {
                txtSoHDN.setText("");
                data_CTHDN.removeAllElements();
                tableCTHDN.setModel(new DefaultTableModel(data_CTHDN,header_CTHDN));
            }
            else if(dao_CTHDN.kTraTonTai(sohd)!=1)
            {
                dao_HDN.delete(sohd);
                JOptionPane.showMessageDialog(this,"Thành Công!","Thông báo",1);
            }
            else if(dao_CTHDN.huyHoaDon(sohd)==1)
            {
                JOptionPane.showMessageDialog(this,"Thành Công!","Thông báo",1);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Lỗi!","Thông báo",1);
            }
            layDuLieuCTHDN(sohd);
            loadDataTabKhoXe();
            loadThongTinLSN();
        }
        txtSoHDN.setText("");
        txtNgayTao.setText("");
        cbMaNCC.setSelectedIndex(-1);
        txtTongNhap.setText("");
        txtTongTien.setText("");
        txtTrangThai.setText("");
        txtGhiChu.setText("");
        IDCTHDN.setText("");
        cbMaXe.setSelectedIndex(0);
        txtSLN.setText("");
        txtGiaNhap.setText("");
    }//GEN-LAST:event_btnHuyHDActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        if(txtSoHDN.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không có hóa đơn nào để thanh toán!","Thông báo",1);
        }
        else
        {
            int sohd=Integer.parseInt(txtSoHDN.getText());
            if(dao_HDN.search(sohd)==null)
            {
                JOptionPane.showMessageDialog(this,"Hóa đơn nhập không tông tại. Vui lòng tạo hóa đơn nhập trước khi thanh toán!","Thông báo",1);
            }
            else
            {
                    if(dao_HDN.thanhToan(sohd)==1)
                {
                   
                    Pojo_HoaDonNhap hd=dao_HDN.search(sohd);
                    loadThongTinLSN();
                    setText(hd);
                    JOptionPane.showMessageDialog(this,"Thành Công!","Thông báo",1);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Lỗi!","Thông báo",1);
                }

                    }
 
        }
        
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnThemCTHDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTHDNActionPerformed
        // TODO add your handling code here:
        if(txtTrangThai.getText().equals("ĐÃ THANH TOÁN"))
        {
            JOptionPane.showMessageDialog(this,"Không thể thêm do Hóa Đơn ĐÃ THANH TOÁN","Lưu ý",2);
        }
        else if(txtSoHDN.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không có Hóa đơn nào để thêm!","Lưu ý",2);
        }
        else if(txtSLN.getText().equals("")||txtGiaNhap.getText().equals("")||cbMaXe.getSelectedItem()==null)
        {
            JOptionPane.showMessageDialog(this,"Lỗi! Kiểm tra lại các trường dữ liệu còn trống.","Lưu ý!",2);
        }    
        else
        {

            int so=Integer.parseInt(txtSoHDN.getText().trim());
            if(dao_HDN.search(so)==null)
            {
                JOptionPane.showMessageDialog(this,"Không tìm thấy hóa đơn. Bạn cần tạo hóa đơn trước khi thêm!","Lưu ý!",2);
            }
            else if(cbMaXe.getSelectedIndex()==0)
            {
                JOptionPane.showMessageDialog(this,"Không có sản phẩm nào được chọn !","Lưu ý",2);
            }
            else
            {
                Pojo_HoaDonNhap hd=new Pojo_HoaDonNhap(Integer.parseInt(txtSoHDN.getText().trim()),cbMaNV.getSelectedItem().toString(), cbMaNCC.getSelectedItem().toString().trim());
                int soluong=Integer.parseInt(txtSLN.getText());
                /*int id=dao_CTHDN.getLast(hd);
                id++;*/
                int id=Integer.parseInt(IDCTHDN.getText().trim());
                Pojo_CTHDN x=new Pojo_CTHDN(Integer.parseInt(txtSoHDN.getText().trim()),id,cbMaXe.getSelectedItem().toString(),soluong,Double.parseDouble(txtGiaNhap.getText()));
                // Pojo_HoaDon hd=new Pojo_HoaDon(txtMaHD.getText(),txtNgayTaoHD.getText(),txtMaNVHD.getText(),txtMaKHHD.getText(),txtMaBanHD.getText(),Float.parseFloat(txtTongTienHD.getText()), txtTrangThaiHD.getText());
                dao_CTHDN.add(x);
                layDuLieuCTHDN(hd.getMahdn());
                Pojo_HoaDonNhap hoadon=dao_HDN.search(x.getMahdn());  
                setText(hoadon);
                int nextid=x.getId();
                nextid++;
                IDCTHDN.setText(String.format("%d", nextid));
                cbMaXe.setSelectedIndex(-1);
                txtSLN.setText("");
                txtGiaNhap.setText("");
                loadDataTabKhoXe();
                loadThongTinLSN();
            }
        }
    }//GEN-LAST:event_btnThemCTHDNActionPerformed

    private void btnXoaCTHDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTHDNActionPerformed
        // TODO add your handling code here:
        try{
            Vector v=(Vector)data_CTHDN.get(tableCTHDN.getSelectedRow());
            int sohd=Integer.parseInt(v.get(0).toString());
            int id=Integer.parseInt(v.get(1).toString());
            String ma=v.get(2).toString();
            int soluong=Integer.parseInt(v.get(3).toString());
            double gianhap=Double.parseDouble(v.get(4).toString());
            double thanhtien=Double.parseDouble(v.get(5).toString());
            Pojo_CTHDN x=new Pojo_CTHDN(sohd, id, ma, soluong, gianhap, thanhtien);
            if(txtTrangThai.getText().equals("ĐÃ THANH TOÁN"))
            {
                 JOptionPane.showMessageDialog(this,"Hóa đơn đã thanh toán. Không thể xóa!","Lưu ý",2);
            }
            else  if(dao_CTHDN.xoaCTHDN(x)==1)
            {
                JOptionPane.showMessageDialog(this,"Thành Công!","Thông báo",1);
                layDuLieuCTHDN(sohd);
                loadThongTinLSN();
                getText();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Lỗi!","Thông báo",2);
            }
        }catch(Exception e){
       
            JOptionPane.showMessageDialog(this,"Vui lòng chọn CTHDN cần xóa từ bảng!","Lưu ý",2);
        }
    }//GEN-LAST:event_btnXoaCTHDNActionPerformed

    private void tableXeMayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableXeMayMouseClicked
        // TODO add your handling code here:
        txtMaXeTabKhoXe.setText("");
        txtTenXeTabKhoXe.setText("");
        txtPhienBanTabKhoXe.setText("");
        txtMauXeTabKhoXe.setText("");
        cbMaLoaiTabKhoXe.setSelectedIndex(-1);
        txtNSXTabKhoXe.setText("");
        cbMaNSX.setSelectedIndex(-1);
        txtNCCTabKhoXe.setText("");
        jComboBox1.setSelectedIndex(-1);
        txtGiaBanTabKhoXe.setText("");
        txtBaoHanhTabKhoXe.setText("");
        txtTonKhoTabKhoXe.setText("");
        int index=tableXeMay.getSelectedRow();
        if(index>=0)
        {
            Vector v=(Vector)data_XM.get(index);
            txtMaXeTabKhoXe.setText(v.get(0).toString().trim());
            txtTenXeTabKhoXe.setText(v.get(1).toString().trim());
            txtPhienBanTabKhoXe.setText(v.get(2).toString().trim());
            txtMauXeTabKhoXe.setText(v.get(3).toString().trim());
            cbMaLoaiTabKhoXe.setSelectedItem(v.get(4).toString().trim());
            txtNSXTabKhoXe.setText(v.get(5).toString().trim());
            cbMaNSX.setSelectedItem(v.get(5).toString().trim());
            txtNCCTabKhoXe.setText(v.get(6).toString().trim());
            jComboBox1.setSelectedItem(v.get(6).toString().trim());
            txtGiaBanTabKhoXe.setText(v.get(7).toString().trim());
            txtBaoHanhTabKhoXe.setText(v.get(8).toString().trim());
            txtTonKhoTabKhoXe.setText(v.get(9).toString().trim());
        }
        
    }//GEN-LAST:event_tableXeMayMouseClicked

    private void tableLSHDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLSHDNMouseClicked
        // TODO add your handling code here:
        int index=tableLSHDN.getSelectedRow();
        if(index>=0)
        {
            Vector v=(Vector)data_LSN.get(index);
            txtSoHDLSN.setText(v.get(0).toString().trim());
            txtMaNVLSN.setText(v.get(1).toString().trim());
            txtNgayNhapLSN.setText(v.get(2).toString().trim());
            txtMaNCCLSN.setText(v.get(3).toString().trim());
            txtSoXeNhapLSN.setText(v.get(4).toString().trim());
            txtTongTienLSN.setText(v.get(5).toString().trim());
            txtTrangThaiLSN.setText(v.get(6).toString().trim());
            txtGhiChuLSN.setText(v.get(7).toString().trim());
        }
    }//GEN-LAST:event_tableLSHDNMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        try
        {
            Pojo_XeMay xe=new Pojo_XeMay(txtMaXeTabKhoXe.getText().trim(),txtTenXeTabKhoXe.getText().trim(),txtPhienBanTabKhoXe.getText().trim(),txtMauXeTabKhoXe.getText().trim(),cbMaLoaiTabKhoXe.getSelectedItem().toString().trim(),cbMaNSX.getSelectedItem().toString().trim(),jComboBox1.getSelectedItem().toString().trim(),Double.parseDouble(txtGiaBanTabKhoXe.getText().trim()),Integer.parseInt(txtBaoHanhTabKhoXe.getText().trim()),Integer.parseInt(txtTonKhoTabKhoXe.getText().trim()));
            dao_XM.update(xe);
            dao_XM.loadData(data_XM);
            loadDataTabKhoXe();
            JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn thông tin cần cập nhật từ bảng","Lưu ý",2);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        txtMaXeTabKhoXe.setText("");
        txtTenXeTabKhoXe.setText("");
        txtPhienBanTabKhoXe.setText("");
        txtMauXeTabKhoXe.setText("");
        cbMaLoaiTabKhoXe.setSelectedIndex(1);
        txtNSXTabKhoXe.setText("");
        cbMaNSX.setSelectedIndex(1);
        txtNCCTabKhoXe.setText("");
        jComboBox1.setSelectedIndex(1);
        txtGiaBanTabKhoXe.setText("");
        txtBaoHanhTabKhoXe.setText("");
        txtTonKhoTabKhoXe.setText("");
        txtMaXeTabKhoXe.requestFocus();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(txtMaXeTabKhoXe.getText().equals("")/*||txtTenXeTabKhoXe.getText().equals("")||txtPhienBanTabKhoXe.getText().equals("")||txtMauXeTabKhoXe.getText().equals("")||txtGiaBanTabKhoXe.getText().equals("")||txtBaoHanhTabKhoXe.getText().equals("")||txtTonKhoTabKhoXe.getText().equals("")*/)
        {
            JOptionPane.showMessageDialog(this,"Chưa đủ thông tin. Vui lòng kiểm tra lại!","Lưu ý",2);   
        }
        else if(dao_XM.kTraMaXe(txtMaXeTabKhoXe.getText().trim())==1)
        {
            JOptionPane.showMessageDialog(this,"Mã xe đã tồn tại. Không thể thêm!","Thông báo",2);
        }
        else
        {
            if(txtTenXeTabKhoXe.getText().equals(""))
            {
                if(dao_XM.themMaXe(txtMaXeTabKhoXe.getText().trim())==1)
                {
                    dao_XM.loadData(data_XM);
                    loadComboBoxMaXe();
                    loadDataTabKhoXe();
                    JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Lỗi. Không thể thêm!","Thông báo",2);
                }
     
            
            }
            else
            {
         
                Pojo_XeMay xe=new Pojo_XeMay(txtMaXeTabKhoXe.getText().trim(),txtTenXeTabKhoXe.getText().trim(),txtPhienBanTabKhoXe.getText().trim(),txtMauXeTabKhoXe.getText().trim(),cbMaLoaiTabKhoXe.getSelectedItem().toString().trim(),cbMaNSX.getSelectedItem().toString().trim(),jComboBox1.getSelectedItem().toString().trim(),Double.parseDouble(txtGiaBanTabKhoXe.getText().trim()),Integer.parseInt(txtBaoHanhTabKhoXe.getText().trim()),Integer.parseInt(txtTonKhoTabKhoXe.getText().trim()));
                if(dao_XM.add(xe)==1)
                {
                  //  dao_XM.add(xe);
                    dao_XM.loadData(data_XM);
                    loadComboBoxMaXe();
                    loadDataTabKhoXe();
                    JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Lỗi. Không thể thêm!","Thông báo",2);
                }
            }
        
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tableLSCTHDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLSCTHDNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableLSCTHDNMouseClicked

    private void btnXemCTHDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemCTHDNActionPerformed
        // TODO add your handling code here:
        try
       {
            int sohd=Integer.parseInt(txtSoHDLSN.getText().trim());
            header_CTHDN.removeAllElements();
            header_CTHDN.add("SOHD");
            header_CTHDN.add("ID");
            header_CTHDN.add("MAXE");
            header_CTHDN.add("SOLUONG");
            header_CTHDN.add("DONGIA");
            header_CTHDN.add("THANHTIEN");
            dao_CTHDN.loadData(data_CTHDN,sohd);
            tableLSCTHDN.setModel(new DefaultTableModel(data_CTHDN, header_CTHDN));
           
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,"Vui lòng chọn Hóa Đơn cần xem từ bảng!","Lưu ý",2);
       }
    }//GEN-LAST:event_btnXemCTHDNActionPerformed

    private void btnHuyHDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHDNActionPerformed
        // TODO add your handling code here:
        try
       {
           int response= JOptionPane.showConfirmDialog(this, "Bạn có thật sự muốn XÓA Hóa Đơn này?", "Thông báo", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            // Now display response result
            if(response == JOptionPane.YES_OPTION)
            {
                int sohd=Integer.parseInt(txtSoHDLSN.getText().trim());
                if(dao_HDN.kiemTraChiTietHoaDonNhap(sohd)==0)
                {
                    if(dao_HDN.delete(sohd)==1)
                    {loadThongTinLSN();
                    layDuLieuCTHDN(sohd);
                    loadDataTabKhoXe();
                    JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                    }
                    else
                        JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                }
                
                else if(dao_HDN.kiemTraChiTietHoaDonNhap(sohd)==1)
                {
                    if(dao_CTHDN.huyHoaDon(sohd)==1)
                    {loadThongTinLSN();
                    layDuLieuCTHDN(sohd);
                    loadDataTabKhoXe();
                    JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                    }else 
                        JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                }
            }
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,"Vui lòng chọn Hóa Đơn Nhập cần hủy từ bảng!","Lưu ý",2);
       }
    }//GEN-LAST:event_btnHuyHDNActionPerformed

    private void btnXoaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaXeActionPerformed
        // TODO add your handling code here:
         try
       {
           int response= JOptionPane.showConfirmDialog(this, "Bạn có thật sự muốn XÓA?", "Thông báo", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            // Now display response result
            if(response == JOptionPane.YES_OPTION)
            {
                String ma=txtMaXeTabKhoXe.getText().trim();
                if(dao_XM.kTraMaXe(ma)==0)
                {
                    JOptionPane.showMessageDialog(this,"Mã xe không tông tại!","Thông báo",1);
                }
                else if(dao_XM.xoaXe(ma)==1)
                {
                    loadDataTabKhoXe();
                    loadComboBox();
                    txtMaXeTabKhoXe.setText("");
                    txtTenXeTabKhoXe.setText("");
                    txtPhienBanTabKhoXe.setText("");
                    txtMauXeTabKhoXe.setText("");
                    cbMaLoaiTabKhoXe.setSelectedIndex(1);
                    txtNSXTabKhoXe.setText("");
                    cbMaNSX.setSelectedIndex(1);
                    txtNCCTabKhoXe.setText("");
                    jComboBox1.setSelectedIndex(1);
                    txtGiaBanTabKhoXe.setText("");
                    txtBaoHanhTabKhoXe.setText("");
                    txtTonKhoTabKhoXe.setText("");
                    JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                }
            }
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,"Vui lòng chọn thông tin cần xóa từ bảng!","Lưu ý",2);
       }
    }//GEN-LAST:event_btnXoaXeActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        if(cbTenNSX.getSelectedItem()==null)
        {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn bộ lọc!","Lưu ý",2);
        }
        else
        {
            String tenhang=cbTenNSX.getSelectedItem().toString();
            dao_XM.danhSachTheoHang(tenhang, data_XM);
            if(data_XM.isEmpty()==true)
            {
                header_XM.removeAllElements();
                data_XM.removeAllElements();
                tableXeMay.setModel(new DefaultTableModel(data_XM,header_XM));
                JOptionPane.showMessageDialog(this,"Không có dữ liệu!","Thông báo",1);
            }
            else
                
            {
                header_XM.removeAllElements();
                header_XM.add("Mã Xe");
                header_XM.add("Tên Xe");
                header_XM.add("Phiên Bản");
                header_XM.add("Màu Xe");
                header_XM.add("Mã Loại");
                header_XM.add("Mã NSX");
                header_XM.add("Mã NCC");
                header_XM.add("Giá Bán");
                header_XM.add("BH");
                header_XM.add("Số Lượng");
                tableXeMay.setModel(new DefaultTableModel(data_XM,header_XM));
            }
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatCaActionPerformed
        // TODO add your handling code here:
        loadDataTabKhoXe();
    }//GEN-LAST:event_btnTatCaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
         String ma=txtSoHDLSN.getText().trim();
        if(ma.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập số Hóa Đơn","Lưu ý",2);
        }
        else
        {
            Pojo_HoaDonNhap x=dao_HDN.search(Integer.parseInt(ma));
            if(x==null)
            {
                JOptionPane.showMessageDialog(this,"Không tìm thấy","Thông báo",1);
            }
            else
            {
                txtSoHDLSN.setText(String.format("%d", x.getMahdn()));
                txtMaNVLSN.setText(x.getManv().trim());
                txtNgayNhapLSN.setText(x.getNgaynhap().trim());
                txtMaNCCLSN.setText(x.getMancc().trim());
                txtSoXeNhapLSN.setText(String.format("%d", x.getTongsoxenhap()));
                txtTongTienLSN.setText(String.format("%f", x.getTongtien()));
                txtTrangThaiLSN.setText(x.getTrangthai().trim());
                txtGhiChuLSN.setText(x.getGhichu().trim());

            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
         String ma=txtMaXeTabKhoXe.getText().trim();
        if(ma.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập mã xe cần tìm!","Lưu ý",2);
        }
        else
        {
            Pojo_XeMay x=dao_XM.search(ma);
            if(x==null)
            {
                JOptionPane.showMessageDialog(this,"Không tìm thấy","Thông báo",1);
            }
            else
            {
                txtMaXeTabKhoXe.setText(x.getMaxe().trim());
                txtTenXeTabKhoXe.setText(x.getTenxe().trim());
                txtPhienBanTabKhoXe.setText(x.getPhienban().trim());
                txtMauXeTabKhoXe.setText(x.getMauxe().trim());
                cbMaLoaiTabKhoXe.setSelectedItem(x.getMaloaixe().trim());
                txtNSXTabKhoXe.setText(x.getMansx().trim());
                txtNCCTabKhoXe.setText(x.getMancc().trim());
                txtGiaBanTabKhoXe.setText(String.format("%f",x.getGiaban()));
                txtBaoHanhTabKhoXe.setText(String.format("%d",x.getSonambh()));
                txtTonKhoTabKhoXe.setText(String.format("%d",x.getTonkho()));
            }
        }
    }//GEN-LAST:event_btnTimActionPerformed

     public void setText(Pojo_HoaDonNhap hd)
    {
        txtNgayTao.setEnabled(true);
        txtTongNhap.setEnabled(true);
        txtTongTien.setEnabled(true);
        txtTrangThai.setEnabled(true);
        txtGhiChu.setEnabled(true);
        txtSoHDN.setText(String.format("%d",hd.getMahdn()));
        cbMaNV.setSelectedItem(hd.getManv().toString().trim());
        cbMaNCC.setSelectedItem(hd.getMancc().toString().trim());
        txtTongNhap.setText(String.format("%d", hd.getTongsoxenhap()));
        txtNgayTao.setText(hd.getNgaynhap().trim());
        txtTongTien.setText(String.format("%f",hd.getTongtien()));
        txtTrangThai.setText(hd.getTrangthai().trim());
        txtGhiChu.setText(hd.getGhichu());
    }
    public void getText()
    {
        txtSoHDN.setText("");
        cbMaNV.setSelectedItem("");
        txtNgayTao.setText("");
        cbMaNCC.setSelectedIndex(-1);
        txtTongTien.setText("");
        txtTrangThai.setText("");
        txtGhiChu.setText("");
        cbMaNV.requestFocus();
        txtNgayTao.setEnabled(false);
        txtTongNhap.setEnabled(false);
        txtTongTien.setEnabled(false);
        txtTrangThai.setEnabled(false);
        txtGhiChu.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDCTHDN;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHoaDonNhapMoi;
    private javax.swing.JButton btnHuyHD;
    private javax.swing.JButton btnHuyHDN;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuHD;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnTatCa;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemCTHDN;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXemCTHDN;
    private javax.swing.JButton btnXoaCTHDN;
    private javax.swing.JButton btnXoaXe;
    private javax.swing.JComboBox<String> cbMaLoaiTabKhoXe;
    private javax.swing.JComboBox<String> cbMaNCC;
    private javax.swing.JComboBox<String> cbMaNSX;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JComboBox<String> cbMaXe;
    private javax.swing.JComboBox<String> cbTenNSX;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableCTHDN;
    private javax.swing.JTable tableLSCTHDN;
    private javax.swing.JTable tableLSHDN;
    private javax.swing.JTable tableXeMay;
    private javax.swing.JTextField txtBaoHanhTabKhoXe;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGhiChuLSN;
    private javax.swing.JTextField txtGiaBanTabKhoXe;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaNCCLSN;
    private javax.swing.JTextField txtMaNVLSN;
    private javax.swing.JTextField txtMaXeTabKhoXe;
    private javax.swing.JTextField txtMauXeTabKhoXe;
    private javax.swing.JTextField txtNCCTabKhoXe;
    private javax.swing.JTextField txtNSXTabKhoXe;
    private javax.swing.JTextField txtNgayNhapLSN;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtPhienBanTabKhoXe;
    private javax.swing.JTextField txtSLN;
    private javax.swing.JTextField txtSoHDLSN;
    private javax.swing.JTextField txtSoHDN;
    private javax.swing.JTextField txtSoXeNhapLSN;
    private javax.swing.JTextField txtTenXeTabKhoXe;
    private javax.swing.JTextField txtTonKhoTabKhoXe;
    private javax.swing.JTextField txtTongNhap;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTongTienLSN;
    private javax.swing.JTextField txtTrangThai;
    private javax.swing.JTextField txtTrangThaiLSN;
    // End of variables declaration//GEN-END:variables
}
