/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_chxemay.Form;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ql_chxemay.DAO.DAO_ChucVu;
import ql_chxemay.DAO.DAO_NCC;
import ql_chxemay.DAO.DAO_NhaSanXuat;
import ql_chxemay.DAO.DAO_NhanVien;
import ql_chxemay.DAO.DAO_TaiKhoan;
import ql_chxemay.POJO.Pojo_NhaCungCap;
import ql_chxemay.POJO.Pojo_NhaSanXuat;
import ql_chxemay.POJO.Pojo_NhanVien;
import ql_chxemay.POJO.Pojo_TaiKhoan;

/**
 *
 * @author Ngo Truong An
 */
public class QuanLi extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLi
     */
    Vector header_TK =new Vector();
    Vector data_TK =new Vector();
    DAO_TaiKhoan dao_TK=new DAO_TaiKhoan();
    Vector data_CV =new Vector();
    DAO_ChucVu dao_CV=new DAO_ChucVu();
    Vector header_NV =new Vector();
    Vector data_NV =new Vector();
    DAO_NhanVien dao_NV=new DAO_NhanVien();
    DAO_NhaSanXuat dao_NSX=new DAO_NhaSanXuat();
    Vector header_NSX =new Vector();
    Vector data_NSX =new Vector();
    DAO_NCC dao_NCC=new DAO_NCC();
    Vector header_NCC =new Vector();
    Vector data_NCC =new Vector();
    public QuanLi() {
        initComponents();
        loadComboBox();
        loadComboBoxCVTabTK();
        loadComboBoxNhomQuyen();
        loadDataNhanVien();
        loadDataQuanLiTK();
        loadDataNSX();
        loadDataNCC();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrGioiTinhNV = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        txtDC = new javax.swing.JTextField();
        txtDT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbMaCV = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNV = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtNgSinh = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNgVL = new javax.swing.JTextField();
        btnNVMoi = new javax.swing.JButton();
        btnLuuNV = new javax.swing.JButton();
        btnCapNhatNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenNgDung = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbNhomQuyen = new javax.swing.JComboBox<>();
        btnTKMoi = new javax.swing.JButton();
        btnLuuTaiKhoan = new javax.swing.JButton();
        btnCapNhatTK = new javax.swing.JButton();
        btnXoaTK = new javax.swing.JButton();
        btnThuHoiQuyen = new javax.swing.JButton();
        btnCapQuyen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTaiKhoan = new javax.swing.JTable();
        cbMaChucVu = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtDTNCC = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDCNCC = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableNCC = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnNVMoi2 = new javax.swing.JButton();
        btnLuuNV2 = new javax.swing.JButton();
        btnCapNhatNV2 = new javax.swing.JButton();
        btnXoaNV2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtMaNSX = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTenNSX = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDTNSX = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableNSX = new javax.swing.JTable();
        btnNVMoi1 = new javax.swing.JButton();
        btnLuuNV1 = new javax.swing.JButton();
        btnCapNhatNV1 = new javax.swing.JButton();
        btnXoaNV1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Quản Lí");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/manager.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("QUẢN LÍ NHÂN VIÊN");

        jLabel7.setText("Mã NV:");

        jLabel8.setText("Họ Tên:");

        jLabel9.setText("Giới Tính:");

        btngrGioiTinhNV.add(radioNam);
        radioNam.setText("Nam");

        btngrGioiTinhNV.add(radioNu);
        radioNu.setText("Nữ");

        jLabel11.setText("Điện Thoại:");

        jLabel12.setText("Địa Chỉ:");

        jLabel13.setText("Mã CV:");

        tableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableNV);

        jLabel14.setText("Ngày Sinh:");

        jLabel15.setText("Ngày Vào Làm:");

        btnNVMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-file-icon (1).png"))); // NOI18N
        btnNVMoi.setText("Mới");
        btnNVMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVMoiActionPerformed(evt);
            }
        });

        btnLuuNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/floppy-icon.png"))); // NOI18N
        btnLuuNV.setText("Lưu");
        btnLuuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuNVActionPerformed(evt);
            }
        });

        btnCapNhatNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-validated-icon (1).png"))); // NOI18N
        btnCapNhatNV.setText("Cập Nhật");
        btnCapNhatNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNVActionPerformed(evt);
            }
        });

        btnXoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete-icon.png"))); // NOI18N
        btnXoaNV.setText("Xóa");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("DANH SÁCH NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel10))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnNVMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnLuuNV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnCapNhatNV)
                .addGap(106, 106, 106)
                .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(radioNam)
                        .addGap(23, 23, 23)
                        .addComponent(radioNu))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtMaNV))
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgVL, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66)
                            .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(txtDT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(radioNam)
                                    .addComponent(radioNu)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNgVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))))
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtNgSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNVMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhatNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Nhân Viên", jPanel1);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("QUẢN LÍ TÀI KHOẢN");

        jLabel1.setText("Tên ĐN:");

        jLabel2.setText("Mật Khẩu:");

        jLabel3.setText("Tên Ng Dùng:");

        jLabel4.setText("Mã Chức Vụ:");

        jLabel6.setText("Nhóm Quyền:");

        cbNhomQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnTKMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-file-icon (1).png"))); // NOI18N
        btnTKMoi.setText("Mới");
        btnTKMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKMoiActionPerformed(evt);
            }
        });

        btnLuuTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/floppy-icon.png"))); // NOI18N
        btnLuuTaiKhoan.setText("Lưu");
        btnLuuTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuTaiKhoanActionPerformed(evt);
            }
        });

        btnCapNhatTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-validated-icon (1).png"))); // NOI18N
        btnCapNhatTK.setText("Cập Nhật");
        btnCapNhatTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTKActionPerformed(evt);
            }
        });

        btnXoaTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete-icon.png"))); // NOI18N
        btnXoaTK.setText("Xóa");
        btnXoaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTKActionPerformed(evt);
            }
        });

        btnThuHoiQuyen.setText("Thu Hồi Quyền");
        btnThuHoiQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuHoiQuyenActionPerformed(evt);
            }
        });

        btnCapQuyen.setText("Cấp Quyền");
        btnCapQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapQuyenActionPerformed(evt);
            }
        });

        tableTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTaiKhoan);

        cbMaChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenNgDung, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(42, 42, 42)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThuHoiQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCapQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnTKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnLuuTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnCapNhatTK)
                                .addGap(59, 59, 59)
                                .addComponent(btnXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(185, Short.MAX_VALUE))))
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenNgDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThuHoiQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhatTK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );

        jTabbedPane1.addTab("Tài Khoản", jPanel2);

        jLabel20.setText("Mã NSX:");

        jLabel21.setText("Tên NSX:");

        jLabel22.setText("Điện Thoại:");

        jLabel23.setText("Địa Chỉ:");

        tableNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNCCMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableNCC);

        btnNVMoi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-file-icon (1).png"))); // NOI18N
        btnNVMoi2.setText("Mới");
        btnNVMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVMoi2ActionPerformed(evt);
            }
        });

        btnLuuNV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/floppy-icon.png"))); // NOI18N
        btnLuuNV2.setText("Lưu");
        btnLuuNV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuNV2ActionPerformed(evt);
            }
        });

        btnCapNhatNV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-validated-icon (1).png"))); // NOI18N
        btnCapNhatNV2.setText("Cập Nhật");
        btnCapNhatNV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNV2ActionPerformed(evt);
            }
        });

        btnXoaNV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete-icon.png"))); // NOI18N
        btnXoaNV2.setText("Xóa");
        btnXoaNV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNV2ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("DANH SÁCH NHÀ CUNG CẤP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnNVMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnLuuNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnCapNhatNV2)
                                .addGap(67, 67, 67)
                                .addComponent(btnXoaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 216, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDTNCC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtTenNCC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDCNCC)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtDCNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNVMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhatNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhà Cung Cấp", jPanel4);

        jLabel17.setText("Mã NSX:");

        jLabel18.setText("Tên NSX:");

        jLabel19.setText("Điện Thoại:");

        tableNSX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNSXMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableNSX);

        btnNVMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-file-icon (1).png"))); // NOI18N
        btnNVMoi1.setText("Mới");
        btnNVMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVMoi1ActionPerformed(evt);
            }
        });

        btnLuuNV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/floppy-icon.png"))); // NOI18N
        btnLuuNV1.setText("Lưu");
        btnLuuNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuNV1ActionPerformed(evt);
            }
        });

        btnCapNhatNV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-validated-icon (1).png"))); // NOI18N
        btnCapNhatNV1.setText("Cập Nhật");
        btnCapNhatNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNV1ActionPerformed(evt);
            }
        });

        btnXoaNV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete-icon.png"))); // NOI18N
        btnXoaNV1.setText("Xóa");
        btnXoaNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNV1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("DANH SÁCH NHÀ SẢN XUẤT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnNVMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnLuuNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnCapNhatNV1)
                                .addGap(67, 67, 67)
                                .addComponent(btnXoaNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel25)))
                .addGap(0, 205, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNSX)
                            .addComponent(txtTenNSX)
                            .addComponent(txtDTNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtMaNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtDTNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNVMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhatNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhà Sản Xuất", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadComboBox()
    {
        dao_CV.loadData(data_CV);
        for(int i=0;i<data_CV.size();i++)
        {
            Vector v=(Vector)data_CV.get(i);
            String item=v.get(0).toString();
            cbMaCV.addItem(item);
        }
        cbMaCV.setSelectedIndex(0);
    }
    public void loadComboBoxCVTabTK()
    {
        dao_CV.loadData(data_CV);
        for(int i=0;i<data_CV.size();i++)
        {
            Vector v=(Vector)data_CV.get(i);
            String item=v.get(0).toString();
            cbMaChucVu.addItem(item);
        }
        cbMaChucVu.setSelectedIndex(0);
    }

    private void tableTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTaiKhoanMouseClicked
        // TODO add your handling code here:
        int index =tableTaiKhoan.getSelectedRow();
        if(index >=0)
        {
            Vector v=(Vector)data_TK.get(index);
            txtTenDN.setText(v.get(0).toString().trim());
            txtMK.setText(v.get(1).toString().trim());
            txtTenNgDung.setText(v.get(2).toString().trim());
            cbMaChucVu.setSelectedItem(v.get(3).toString().trim());
            cbNhomQuyen.setSelectedItem(v.get(4).toString().trim());
        }
    }//GEN-LAST:event_tableTaiKhoanMouseClicked

    private void btnCapNhatTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTKActionPerformed
        // TODO add your handling code here:
        if(txtTenDN.getText().trim().equals("")||txtMK.getText().trim().equals("")||txtTenNgDung.getText().trim().equals(""))
        {
             JOptionPane.showMessageDialog(this,"Chưa đủ thông tin. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else
        {
            Pojo_TaiKhoan x=new Pojo_TaiKhoan(txtTenDN.getText().trim(),txtMK.getText().trim(),txtTenNgDung.getText().trim(),cbMaCV.getSelectedItem().toString(),cbNhomQuyen.getSelectedItem().toString());
            if(dao_TK.capNhatTaiKhoan(x)==1)
            {
                loadDataQuanLiTK();
                JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
            }
            else
                 JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Lưu ý",2);
        }
    }//GEN-LAST:event_btnCapNhatTKActionPerformed

    private void tableNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNVMouseClicked
        // TODO add your handling code here:
        int index=tableNV.getSelectedRow();
        if(index>=0)
        {
            txtMaNV.setEditable(false);
            Vector v=(Vector) data_NV.get(index);
            txtMaNV.setText(v.get(0).toString().trim());
            txtTenNV.setText(v.get(1).toString().trim());
            if(v.get(2).toString().trim().equals("Nam"))
            radioNam.setSelected(true);
            else
            radioNu.setSelected(true);
           /* try {
                Date ngsinh=(Date) new SimpleDateFormat("yyyy-MM-dd").parse((String)tableNV.getValueAt(index,3));
                NgaySinhChooser.setDate(ngsinh);
            } catch (ParseException ex) {
                Logger.getLogger(Panel_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            txtNgSinh.setText(v.get(3).toString().trim());
            txtDT.setText(v.get(4).toString().trim());
            txtDC.setText(v.get(5).toString().trim());
           /* try {
                Date ngvl=(Date) new SimpleDateFormat("yyyy-MM-dd").parse((String)tableNV.getValueAt(index,6));
                NgVLChooser.setDate(ngvl);
            } catch (ParseException ex) {
                Logger.getLogger(Panel_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }*/
           txtNgVL.setText(v.get(6).toString().trim());
           cbMaCV.setSelectedItem(v.get(7).toString().trim());

        }
    }//GEN-LAST:event_tableNVMouseClicked

    private void btnCapNhatNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNVActionPerformed
        // TODO add your handling code here:
       if(txtMaNV.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(this,"Vui lòng chọn thông tin cần cập nhật từ bảng","Lưu ý",2);   
            }
            else
            {
                String manv=txtMaNV.getText().trim();
                String hoten=txtTenNV.getText().trim();
                String gioitinh;
                if(radioNam.isSelected()==true)
                    gioitinh="Nam";
                else gioitinh="Nữ";
                String ngsinh=txtNgSinh.getText().trim();
                String dc=txtDC.getText().trim();
                String dt=txtDT.getText().trim();
                String ngvl=txtNgVL.getText().trim();
                String macv=cbMaCV.getSelectedItem().toString();
                String nhomquyen=cbNhomQuyen.getSelectedItem().toString();
                Pojo_NhanVien x=new Pojo_NhanVien(manv, hoten,gioitinh,ngsinh,dt,dc,ngvl,macv);
                if(dao_NV.kTraTonTai(x.getManv())==0)
                {
                     JOptionPane.showMessageDialog(this,"Mã Nhân Viên này không tồn tại!","Thông báo",2);
                }
                else
                {
                    if(dao_NV.update(x)==1)
                    {
                        JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                        loadDataNhanVien();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                    }
                }
                   
                    
            }
       
    }//GEN-LAST:event_btnCapNhatNVActionPerformed

    private void btnNVMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVMoiActionPerformed
        // TODO add your handling code here:
        txtMaNV.setEditable(true);
        txtMaNV.setText("");
        txtTenNV.setText("");
        radioNam.setSelected(true);
        txtNgSinh.setText("");
        txtDC.setText("");
        txtDT.setText("");
        txtNgVL.setText("");
        cbMaCV.setSelectedItem("NO");
        txtMaNV.requestFocus();
    }//GEN-LAST:event_btnNVMoiActionPerformed

    private void btnLuuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuNVActionPerformed
        // TODO add your handling code here:
        if(txtMaNV.getText().trim().equals("")||txtTenNV.getText().trim().equals("")||txtNgSinh.getText().trim().equals("")||txtDC.getText().trim().equals("")||txtDT.getText().trim().equals("")||txtNgVL.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Chưa nhập đủ thông tin. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else if(btngrGioiTinhNV.getSelection()==null)
        {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn giới tính","Lưu ý",2);
        }
        else
        {
            String gioitinh;
            if(radioNam.isSelected()==true)
            {
                gioitinh="Nam";
            }
            else
            {
                gioitinh="Nữ";
            }
                Pojo_NhanVien x=new Pojo_NhanVien(txtMaNV.getText().trim(), txtTenNV.getText().trim(),gioitinh, txtNgSinh.getText().trim(),txtDT.getText().trim(),txtDC.getText().trim(),txtNgVL.getText().trim(),cbMaCV.getSelectedItem().toString());
                if(dao_NV.kTraTonTai(txtMaNV.getText().trim())==1)
                {
                    JOptionPane.showMessageDialog(this,"Mã nhân viên đã tồn tại!","Thông báo",2);
                }
                else if(dao_NV.kTraTonTai(txtMaNV.getText().trim())==0)
                {
                    if(dao_NV.add(x)==1)
                    {
                      loadDataNhanVien();
                      JOptionPane.showMessageDialog(this,"Thành Công!","Thông báo",1);  
                      
                    }
                     else
                    {
                        JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                    }
    
                }              
        }
    }//GEN-LAST:event_btnLuuNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        // TODO add your handling code here:
       try{
                    int index=tableNV.getSelectedRow();
                    Vector v=(Vector)data_NV.get(index);
                    String ma=v.get(0).toString();
                  
                        if(dao_NV.delete(ma)==1)
                        {
                            loadDataNhanVien();
                            JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                        }
                        else
                             JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                   
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,"Vui lòng chọn thông tin nhân viên cần xóa từ bảng","Lưu ý",2);
       }
        
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnTKMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKMoiActionPerformed
        // TODO add your handling code here:
        txtTenDN.setText("");
        txtTenDN.requestFocus();
        txtMK.setText("");
        txtTenNgDung.setText("");
        cbMaChucVu.setSelectedItem("NO");
        cbNhomQuyen.setSelectedItem("CHƯA CẤP QUYỀN");
    }//GEN-LAST:event_btnTKMoiActionPerformed

    private void btnLuuTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuTaiKhoanActionPerformed
        // TODO add your handling code here:
        if(txtTenDN.getText().trim().equals("")||txtMK.getText().trim().equals("")||txtTenNgDung.getText().trim().equals(""))
        {
             JOptionPane.showMessageDialog(this,"Chưa nhập đủ thông tin. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else
        {
            Pojo_TaiKhoan x=new Pojo_TaiKhoan(txtTenDN.getText().trim(),txtMK.getText().trim(),txtTenNgDung.getText().trim(),cbMaCV.getSelectedItem().toString(),cbNhomQuyen.getSelectedItem().toString());
            if(dao_TK.kTraTonTai(x)==0)
            {
                if(dao_TK.taoTaiKhoan(x)==1)
                {
                    loadDataQuanLiTK();
                    JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                }
                else
                     JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Lưu ý",2);
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"Tên đăng nhập đã tồn tại!\nVui lòng chọn tên đăng nhập khác.","Lưu ý",2);
            }
        }
    }//GEN-LAST:event_btnLuuTaiKhoanActionPerformed

    private void btnCapQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapQuyenActionPerformed
        // TODO add your handling code here:
        if(txtTenDN.getText().trim().equals("")||txtMK.getText().trim().equals("")||txtTenNgDung.getText().trim().equals(""))
        {
             JOptionPane.showMessageDialog(this,"Không tìm thấy thông tin tài khoản người dùng. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else
        {
            Pojo_TaiKhoan x=new Pojo_TaiKhoan(txtTenDN.getText().trim(),txtMK.getText().trim(),txtTenNgDung.getText().trim(),cbMaChucVu.getSelectedItem().toString(),cbNhomQuyen.getSelectedItem().toString());
            if(dao_TK.capQuyen(x)==1)
            {
                loadDataQuanLiTK();
                cbMaChucVu.setSelectedItem(x.getMachucvu());
                cbNhomQuyen.setSelectedItem(x.getNhomquyen());
                loadDataNhanVien();
                JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
            }
            else
                 JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Lưu ý",2);
        }
    }//GEN-LAST:event_btnCapQuyenActionPerformed

    private void btnThuHoiQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuHoiQuyenActionPerformed
        // TODO add your handling code here:
        if(txtTenDN.getText().trim().equals("")||txtMK.getText().trim().equals("")||txtTenNgDung.getText().trim().equals(""))
        {
             JOptionPane.showMessageDialog(this,"Không tìm thấy thông tin tài khoản người dùng. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else
        {
            Pojo_TaiKhoan x=new Pojo_TaiKhoan(txtTenDN.getText().trim(),txtMK.getText().trim(),txtTenNgDung.getText().trim(),cbMaChucVu.getSelectedItem().toString(),cbNhomQuyen.getSelectedItem().toString());
            if(dao_TK.thuHoiQuyen(x)==1)
            {
                loadDataQuanLiTK();
                cbMaChucVu.setSelectedItem("NO");
                cbNhomQuyen.setSelectedItem("CHƯA CẤP QUYỀN");
                loadDataNhanVien();
                JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                
            }
            else
                 JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Lưu ý",2);
        }
    }//GEN-LAST:event_btnThuHoiQuyenActionPerformed

    private void btnXoaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTKActionPerformed
        // TODO add your handling code here:
        if(txtTenDN.getText().trim().equals("")||txtMK.getText().trim().equals("")||txtTenNgDung.getText().trim().equals(""))
        {
             JOptionPane.showMessageDialog(this,"Không tìm thấy thông tin tài khoản người dùng. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else
        {
            Pojo_TaiKhoan x=new Pojo_TaiKhoan(txtTenDN.getText().trim(),txtMK.getText().trim(),txtTenNgDung.getText().trim(),cbMaChucVu.getSelectedItem().toString(),cbNhomQuyen.getSelectedItem().toString());
            if(dao_TK.xoaTaiKhoan(x)==1)
            {
                loadDataQuanLiTK();
                JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                txtTenDN.setText("");
                txtMK.setText("");
                txtTenNgDung.setText("");
                cbMaChucVu.setSelectedIndex(0);
                cbNhomQuyen.setSelectedIndex(0);
            }
            else
                 JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Lưu ý",2);
        }
    }//GEN-LAST:event_btnXoaTKActionPerformed

    private void btnNVMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVMoi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNVMoi1ActionPerformed

    private void btnLuuNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuNV1ActionPerformed
        // TODO add your handling code here:
        if(txtMaNSX.getText().trim().equals("")||txtTenNSX.getText().trim().equals("")||txtDTNSX.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Chưa nhập đủ thông tin. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else
        {
            
                Pojo_NhaSanXuat x=new Pojo_NhaSanXuat(txtMaNSX.getText().trim(), txtTenNSX.getText().trim(), txtDTNSX.getText().trim());
                if(dao_NSX.kTraTonTai(txtMaNSX.getText().trim())==1)
                {
                    JOptionPane.showMessageDialog(this,"Mã NSX đã tồn tại!","Thông báo",2);
                }
                else if(dao_NSX.kTraTonTai(txtMaNSX.getText().trim())==0)
                {
                    if(dao_NSX.add(x)==1)
                    {
                      loadDataNSX();
                      JOptionPane.showMessageDialog(this,"Thành Công!","Thông báo",1);  
                      
                    }
                     else
                    {
                        JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                    }
    
                }              
        }
    }//GEN-LAST:event_btnLuuNV1ActionPerformed

    private void btnCapNhatNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNV1ActionPerformed
        // TODO add your handling code here:
         
                if(txtMaNCC.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(this,"Mã NSX trống","Lưu ý",2); 
                }
                else if(txtTenNSX.equals("")||txtDTNSX.equals(""))
                {
                    JOptionPane.showMessageDialog(this,"Vui lòng điền đầy thủ thông tin!","Lưu ý",2); 
                }
                else
                {
                    Pojo_NhaSanXuat x=new Pojo_NhaSanXuat(txtMaNSX.getText().trim(), txtTenNSX.getText().trim(), txtDTNSX.getText().trim());
                     if(dao_NSX.kTraTonTai(x.getMansx())==0)
                     {
                          JOptionPane.showMessageDialog(this,"Mã Nhà Sản Xuất này không tồn tại!","Thông báo",2);
                     }
                     else
                     {
                         if(dao_NSX.update(x)==1)
                         {
                             JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                             loadDataNCC();
                         }
                         else
                         {
                             JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                         }
                     }
                }

    }//GEN-LAST:event_btnCapNhatNV1ActionPerformed

    private void btnXoaNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNV1ActionPerformed
        // TODO add your handling code here:
        try{
                    int index=tableNSX.getSelectedRow();
                    Vector v=(Vector)data_NSX.get(index);
                    String ma=v.get(0).toString();
                  
                        if(dao_NSX.delete(ma)==1)
                        {
                            loadDataNSX();
                            JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                            txtMaNSX.setText("");
                            txtTenNSX.setText("");
                            txtDTNSX.setText("");
                        }
                        else
                             JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                   
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,"Vui lòng chọn thông tin nhân viên cần xóa từ bảng","Lưu ý",2);
       }
    }//GEN-LAST:event_btnXoaNV1ActionPerformed

    private void tableNSXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNSXMouseClicked
        // TODO add your handling code here:
        int index =tableNSX.getSelectedRow();
        if(index >=0)
        {
            Vector v=(Vector)data_NSX.get(index);
            txtMaNSX.setText(v.get(0).toString().trim());
            txtTenNSX.setText(v.get(1).toString().trim());
            txtDTNSX.setText(v.get(2).toString().trim());
            
        }
    }//GEN-LAST:event_tableNSXMouseClicked

    private void btnNVMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVMoi2ActionPerformed
        // TODO add your handling code here:
        txtMaNCC.setText("");
        txtTenNCC.setText("");
        txtDTNCC.setText("");
        txtDCNCC.setText("");
        txtMaNCC.requestFocus();
        
    }//GEN-LAST:event_btnNVMoi2ActionPerformed

    private void btnLuuNV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuNV2ActionPerformed
        // TODO add your handling code here:
        if(txtMaNCC.getText().trim().equals("")||txtTenNCC.getText().trim().equals("")||txtDTNCC.getText().trim().equals("")||txtDCNCC.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Chưa nhập đủ thông tin. Vui lòng kiểm tra lại!","Lưu ý",2);
        }
        else
        {
            
                Pojo_NhaCungCap x=new Pojo_NhaCungCap(txtMaNCC.getText().trim(), txtTenNCC.getText().trim(), txtDTNCC.getText().trim(), txtDCNCC.getText().trim());
                if(dao_NCC.kTraTonTai(txtMaNCC.getText().trim())==1)
                {
                    JOptionPane.showMessageDialog(this,"Mã NCC đã tồn tại!","Thông báo",2);
                }
                else if(dao_NCC.kTraTonTai(txtMaNCC.getText().trim())==0)
                {
                    if(dao_NCC.add(x)==1)
                    {
                      loadDataNCC();
                      JOptionPane.showMessageDialog(this,"Thành Công!","Thông báo",1);  
                      
                    }
                     else
                    {
                        JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                    }
    
                }              
        }
    }//GEN-LAST:event_btnLuuNV2ActionPerformed

    private void btnCapNhatNV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNV2ActionPerformed
        // TODO add your handling code here:
        
                
                if(txtMaNCC.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(this,"Mã NCC trống","Lưu ý",2); 
                }
                else if(txtTenNCC.getText().equals("")||txtDTNCC.getText().equals("")||txtDCNCC.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(this,"Vui lòng điền đầy thủ thông tin!","Lưu ý",2); 
                }
                else
                {
                    Pojo_NhaCungCap x=new Pojo_NhaCungCap(txtMaNCC.getText().trim(), txtTenNCC.getText().trim(), txtDTNCC.getText().trim(), txtDCNCC.getText().trim());
                    if(dao_NCC.kTraTonTai(x.getMancc())==0)
                    {
                         JOptionPane.showMessageDialog(this,"Mã Nhà Cung Cấp này không tồn tại!","Thông báo",2);
                    }
                    else
                    {
                        if(dao_NCC.update(x)==1)
                        {
                            JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                            loadDataNSX();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                        }
                    }
                }
              
    }//GEN-LAST:event_btnCapNhatNV2ActionPerformed

    private void btnXoaNV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNV2ActionPerformed
        // TODO add your handling code here:
        try{
                    int index=tableNCC.getSelectedRow();
                    Vector v=(Vector)data_NCC.get(index);
                    String ma=v.get(0).toString();
                  
                        if(dao_NCC.delete(ma)==1)
                        {
                            loadDataNCC();
                            JOptionPane.showMessageDialog(this,"Thành công!","Thông báo",1);
                            txtMaNCC.setText("");
                            txtTenNCC.setText("");
                            txtDTNCC.setText("");
                            txtDCNCC.setText("");
                        }
                        else
                             JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Thông báo",2);
                   
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,"Vui lòng chọn thông tin nhân viên cần xóa từ bảng","Lưu ý",2);
       }
        
    }//GEN-LAST:event_btnXoaNV2ActionPerformed

    private void tableNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNCCMouseClicked
        // TODO add your handling code here:
         int index =tableNCC.getSelectedRow();
        if(index >=0)
        {
            Vector v=(Vector)data_NCC.get(index);
            txtMaNCC.setText(v.get(0).toString().trim());
            txtTenNCC.setText(v.get(1).toString().trim());
            txtDTNCC.setText(v.get(2).toString().trim());
            txtDCNCC.setText(v.get(2).toString().trim());
            
        }
    }//GEN-LAST:event_tableNCCMouseClicked

     public void loadComboBoxNhomQuyen()
    {
        dao_CV.loadData(data_CV);
        for(int i=0;i<data_CV.size();i++)
        {
            Vector v=(Vector)data_CV.get(i);
            String item=v.get(2).toString();
            cbNhomQuyen.addItem(item);
        }
        cbNhomQuyen.setSelectedIndex(0);
    }

     public void loadDataNhanVien()
     {
        header_NV.removeAllElements();
        header_NV.add("MANV");
        header_NV.add("HOTEN");
        header_NV.add("GIOITINH");
        header_NV.add("NGAYSINH");
        header_NV.add("DIACHI");
        header_NV.add("DIENTHOAI");
        header_NV.add("NGAYVL");
        header_NV.add("MACV");
        dao_NV.loadData(data_NV);
        tableNV.setModel(new DefaultTableModel(data_NV, header_NV));
        
     }
     public void loadDataQuanLiTK()
     {
        header_TK.removeAllElements();
        header_TK.add("TENDN");
        header_TK.add("MATKHAU");
        header_TK.add("TENNGDUNG");
        header_TK.add("MACV");
        header_TK.add("NHOMQUYEN");
        dao_TK.loadData(data_TK);
        tableTaiKhoan.setModel(new DefaultTableModel(data_TK, header_TK));
     }
     public void loadDataNSX()
     {
         header_NSX.removeAllElements();
         header_NSX.add("Mã NSX");
         header_NSX.add("Tên NSX");
         header_NSX.add("Điện thoại");
         dao_NSX.loadData(data_NSX);
         tableNSX.setModel(new DefaultTableModel(data_NSX,header_NSX));
     }
      public void loadDataNCC()
     {
         header_NCC.removeAllElements();
         header_NCC.add("Mã NCC");
         header_NCC.add("Tên NCC");
         header_NCC.add("Điện thoại");
         header_NCC.add("Địa Chỉ");
         dao_NCC.loadData(data_NCC);
         tableNCC.setModel(new DefaultTableModel(data_NCC,header_NCC));
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatNV;
    private javax.swing.JButton btnCapNhatNV1;
    private javax.swing.JButton btnCapNhatNV2;
    private javax.swing.JButton btnCapNhatTK;
    private javax.swing.JButton btnCapQuyen;
    private javax.swing.JButton btnLuuNV;
    private javax.swing.JButton btnLuuNV1;
    private javax.swing.JButton btnLuuNV2;
    private javax.swing.JButton btnLuuTaiKhoan;
    private javax.swing.JButton btnNVMoi;
    private javax.swing.JButton btnNVMoi1;
    private javax.swing.JButton btnNVMoi2;
    private javax.swing.JButton btnTKMoi;
    private javax.swing.JButton btnThuHoiQuyen;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JButton btnXoaNV1;
    private javax.swing.JButton btnXoaNV2;
    private javax.swing.JButton btnXoaTK;
    private javax.swing.ButtonGroup btngrGioiTinhNV;
    private javax.swing.JComboBox<String> cbMaCV;
    private javax.swing.JComboBox<String> cbMaChucVu;
    private javax.swing.JComboBox<String> cbNhomQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JTable tableNCC;
    private javax.swing.JTable tableNSX;
    private javax.swing.JTable tableNV;
    private javax.swing.JTable tableTaiKhoan;
    private javax.swing.JTextField txtDC;
    private javax.swing.JTextField txtDCNCC;
    private javax.swing.JTextField txtDT;
    private javax.swing.JTextField txtDTNCC;
    private javax.swing.JTextField txtDTNSX;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtMaNSX;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgSinh;
    private javax.swing.JTextField txtNgVL;
    private javax.swing.JTextField txtTenDN;
    private javax.swing.JTextField txtTenNCC;
    private javax.swing.JTextField txtTenNSX;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenNgDung;
    // End of variables declaration//GEN-END:variables
}
