/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_chxemay.Form;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ql_chxemay.DAO.DAO_HoaDon;
import ql_chxemay.DAO.DAO_HoaDonNhap;
import ql_chxemay.DAO.DAO_NhaSanXuat;
import ql_chxemay.DAO.DAO_ThongKe;

/**
 *
 * @author Ngo Truong An
 */
public class ThongKe extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongKe
     */
    DAO_HoaDonNhap dao_HDN=new DAO_HoaDonNhap();
    DAO_HoaDon dao_HD=new DAO_HoaDon();
    Vector header_TKNhapHang=new Vector();
    Vector data_TKNhapHang=new Vector();
    DAO_ThongKe dao_ThongKe=new DAO_ThongKe();
     Vector header_DoanhThu=new Vector();
    Vector data_DoanhThu=new Vector();
     DAO_NhaSanXuat dao_NSX=new DAO_NhaSanXuat();
    Vector data_NSX=new Vector();
     Vector header_Kho=new Vector();
    Vector data_Kho=new Vector();
    public ThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTKNhapHang = new javax.swing.JTable();
        btnThongKeNhapHang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbThangNhap = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtKetQua = new javax.swing.JTextField();
        btnTinhTongDoanhThu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamTinhTongDoanhThu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnTinhTBDoanhThu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbThangDoanhThu = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDoanhThu = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtSLXeBan = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Thống Kê");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tools-2-icon.png"))); // NOI18N

        jLabel1.setText("Nhập năm:");

        tableTKNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableTKNhapHang);

        btnThongKeNhapHang.setText("Thống kê");
        btnThongKeNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeNhapHangActionPerformed(evt);
            }
        });

        jLabel7.setText("Tháng:");

        cbThangNhap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));

        jLabel8.setText("Tổng nhập:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Thống Kê Nhập Hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbThangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnThongKeNhapHang))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKeNhapHang)
                    .addComponent(jLabel7)
                    .addComponent(cbThangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhập Hàng", jPanel1);

        btnTinhTongDoanhThu.setText("Tổng Doanh Thu");
        btnTinhTongDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTongDoanhThuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Thống Kê Doanh Thu");

        jLabel4.setText("Nhập Năm:");

        txtNamTinhTongDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamTinhTongDoanhThuActionPerformed(evt);
            }
        });

        jLabel5.setText("Kết Quả:");

        btnTinhTBDoanhThu.setText("Trung Bình Doanh Thu");
        btnTinhTBDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTBDoanhThuActionPerformed(evt);
            }
        });

        jLabel2.setText("Tháng:");

        cbThangDoanhThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamTinhTongDoanhThu)
                            .addComponent(cbThangDoanhThu, 0, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTinhTBDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTinhTongDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtKetQua))
                .addGap(151, 151, 151))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNamTinhTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhTongDoanhThu))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbThangDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhTBDoanhThu))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        tableDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDoanhThu);

        jLabel6.setText("Số Lượng Xe Đã Bán:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtSLXeBan, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSLXeBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doanh Thu", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeNhapHangActionPerformed
        // TODO add your handling code here:
       /* header_TKNhapHang.removeAllElements();
        header_TKNhapHang.add("MÃ HĐN");
        header_TKNhapHang.add("NGÀY NHẬP");
        header_TKNhapHang.add("MÃ XE");
        header_TKNhapHang.add("NHÀ CUNG CẤP");
        header_TKNhapHang.add("SỐ LƯỢNG NHẬP");
        if(dao_HDN.kiemTraNam(Integer.parseInt(txtNamNhap.getText().trim()))==1)
        {
            dao_ThongKe.thongKeNhapHangNam(Integer.parseInt(txtNamNhap.getText().trim()), data_TKNhapHang);
            tableTKNhapHang.setModel(new DefaultTableModel(data_TKNhapHang,header_TKNhapHang));
        }
        else if(dao_HDN.kiemTraNam(Integer.parseInt(txtNamNhap.getText().trim()))==0)
        {
               JOptionPane.showMessageDialog(this,"Không có dữ liệu!","Thông báo",1);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Có lỗi xảy ra!","Lưu ý",2);
        }*/
        if(txtNamNhap.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập năm!","Lưu ý",2);
            
        }
        else if(Integer.parseInt(cbThangNhap.getSelectedItem().toString())==0)
        {
            dao_ThongKe.thongKeNhapTheoNam(Integer.parseInt(txtNamNhap.getText().trim()), data_TKNhapHang);
             if(data_TKNhapHang.isEmpty()==true)
            {
                resetTableTKNhapHang();
                jTextField1.setText("");
                JOptionPane.showMessageDialog(this,"Không có dữ liệu!","Thông báo",1);
                
                 
            }
            else
            {       
                header_TKNhapHang.removeAllElements();
                header_TKNhapHang.add("MÃ HĐN");
                header_TKNhapHang.add("NGÀY NHẬP");
                header_TKNhapHang.add("MÃ XE");
                header_TKNhapHang.add("NHÀ CUNG CẤP");
                header_TKNhapHang.add("SỐ LƯỢNG NHẬP");
                tableTKNhapHang.setModel(new DefaultTableModel(data_TKNhapHang,header_TKNhapHang));
                jTextField1.setText(String.format("%d",dao_ThongKe.tinhTongNhapNam(Integer.parseInt(txtNamNhap.getText().trim()))));
            }
            
        }
        else
        {
            
            dao_ThongKe.thongKeNhapTheoThang(Integer.parseInt(txtNamNhap.getText().trim()),Integer.parseInt(cbThangNhap.getSelectedItem().toString()), data_TKNhapHang);
            if(data_TKNhapHang.isEmpty()==true)
            {
                resetTableTKNhapHang();
                jTextField1.setText("");
                JOptionPane.showMessageDialog(this,"Không có dữ liệu!","Thông báo",1);
                
            }
            else
            {       
               header_TKNhapHang.removeAllElements();
                header_TKNhapHang.add("MÃ HĐN");
                header_TKNhapHang.add("NGÀY NHẬP");
                header_TKNhapHang.add("MÃ XE");
                header_TKNhapHang.add("NHÀ CUNG CẤP");
                header_TKNhapHang.add("SỐ LƯỢNG NHẬP");
                tableTKNhapHang.setModel(new DefaultTableModel(data_TKNhapHang,header_TKNhapHang));
                jTextField1.setText(String.format("%d",dao_ThongKe.tinhTongNhapThang(Integer.parseInt(txtNamNhap.getText().trim()),Integer.parseInt(cbThangNhap.getSelectedItem().toString()))));
            }
        }
            
         
    }//GEN-LAST:event_btnThongKeNhapHangActionPerformed

   /*   public void loadComboBoxNSX()
    {
        dao_NSX.loadData(data_NSX);
        for(int i=0;i<data_NSX.size();i++)
        {
            Vector v=(Vector)data_NSX.get(i);
            String item=v.get(1).toString();
            cbTenNSX.addItem(item);
        }
        cbTenNSX.setSelectedIndex(-1);
    }
       public void loadComboBoxTinhTrang()
    {
        cbTinhTrang.addItem("CÒN HÀNG");
        cbTinhTrang.addItem("SẮP HẾT HÀNG");
        cbTinhTrang.addItem("HẾT HÀNG");
        cbTinhTrang.setSelectedIndex(-1);
    }*/
    private void txtNamTinhTongDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamTinhTongDoanhThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamTinhTongDoanhThuActionPerformed

    private void btnTinhTongDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTongDoanhThuActionPerformed
        // TODO add your handling code here:

        if(txtNamTinhTongDoanhThu.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập năm!","Lưu ý",2);
        }
        else if(Integer.parseInt(cbThangDoanhThu.getSelectedItem().toString())==0)
        {
            dao_ThongKe.thongKeBanTheoNam(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()), data_DoanhThu);
            if(data_DoanhThu.isEmpty()==true)
            {
                resetTableDoanhThu();
                txtSLXeBan.setText("");
                JOptionPane.showMessageDialog(this,"Không có dữ liệu!","Thông báo",1);
                 
            }
            else
            {       
                header_DoanhThu.removeAllElements();
                header_DoanhThu.add("Mã HĐ");
                header_DoanhThu.add("Ngày Tạo");
                header_DoanhThu.add("Tên Khách Hàng");
                header_DoanhThu.add("Mã Xe");
                header_DoanhThu.add("Số Lượng");
                header_DoanhThu.add("Thành Tiền");
                tableDoanhThu.setModel(new DefaultTableModel(data_DoanhThu,header_DoanhThu));
                txtKetQua.setText(String.format("%f",dao_ThongKe.tinhTongDoanhThuNam(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()))));
                txtSLXeBan.setText(String.format("%d",dao_ThongKe.tinhTongBanNam(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()))));
            }
        }
        else
        {
            
            dao_ThongKe.thongKeBanTheoThang(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()),Integer.parseInt(cbThangDoanhThu.getSelectedItem().toString()), data_DoanhThu);
            if(data_DoanhThu.isEmpty()==true)
            {
                resetTableDoanhThu();
                txtSLXeBan.setText("");
                JOptionPane.showMessageDialog(this,"Không có dữ liệu!","Thông báo",1);
                
            }
            else
            {
                header_DoanhThu.removeAllElements();
                header_DoanhThu.add("Mã HĐ");
                header_DoanhThu.add("Ngày Tạo");
                header_DoanhThu.add("Tên Khách Hàng");
                header_DoanhThu.add("Mã Xe");
                header_DoanhThu.add("Số Lượng");
                header_DoanhThu.add("Thành Tiền");
                tableDoanhThu.setModel(new DefaultTableModel(data_DoanhThu,header_DoanhThu));
                txtKetQua.setText(String.format("%f",dao_ThongKe.tinhTongDoanhThuThang(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()),Integer.parseInt(cbThangDoanhThu.getSelectedItem().toString()))));
                txtSLXeBan.setText(String.format("%d",dao_ThongKe.tinhTongBanThang(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()),Integer.parseInt(cbThangDoanhThu.getSelectedItem().toString()))));
            }
        }
    }//GEN-LAST:event_btnTinhTongDoanhThuActionPerformed
public void resetTableDoanhThu()
{
    header_DoanhThu.removeAllElements();
    data_DoanhThu.removeAllElements();
    tableDoanhThu.setModel(new DefaultTableModel(data_DoanhThu,header_DoanhThu));
}
public void resetTableTKNhapHang()
{
    header_TKNhapHang.removeAllElements();
    data_TKNhapHang.removeAllElements();
    tableTKNhapHang.setModel(new DefaultTableModel(data_TKNhapHang,header_TKNhapHang));
}
    private void btnTinhTBDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTBDoanhThuActionPerformed
        // TODO add your handling code here:
        if(txtNamTinhTongDoanhThu.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập năm!","Lưu ý",2);
            
        }
        else if(Integer.parseInt(cbThangDoanhThu.getSelectedItem().toString())==0)
        {
            dao_ThongKe.thongKeBanTheoNam(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()), data_DoanhThu);
            if(data_DoanhThu.isEmpty()==true)
            {
                resetTableDoanhThu();
                JOptionPane.showMessageDialog(this,"Không có dữ liệu!","Thông báo",1);
                            }
            else
            {       
                header_DoanhThu.removeAllElements();
                header_DoanhThu.add("Mã HĐ");
                header_DoanhThu.add("Ngày Tạo");
                header_DoanhThu.add("Tên Khách Hàng");
                header_DoanhThu.add("Mã Xe");
                header_DoanhThu.add("Số Lượng");
                header_DoanhThu.add("Thành Tiền");
                tableDoanhThu.setModel(new DefaultTableModel(data_DoanhThu,header_DoanhThu));
                txtKetQua.setText(String.format("%f",dao_ThongKe.tinhTBDoanhThuNam(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()))));
                txtSLXeBan.setText(String.format("%d",dao_ThongKe.tinhTongBanNam(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()))));
            }
        }
        else
        {
            
            dao_ThongKe.thongKeBanTheoThang(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()),Integer.parseInt(cbThangDoanhThu.getSelectedItem().toString()), data_DoanhThu);
            if(data_DoanhThu.isEmpty()==true)
            {
                resetTableDoanhThu();
                 JOptionPane.showMessageDialog(this,"Không có dữ liệu!","Thông báo",1);
                
            }
            else
            {
                header_DoanhThu.removeAllElements();
                header_DoanhThu.add("Mã HĐ");
                header_DoanhThu.add("Ngày Tạo");
                header_DoanhThu.add("Tên Khách Hàng");
                header_DoanhThu.add("Mã Xe");
                header_DoanhThu.add("Số Lượng");
                header_DoanhThu.add("Thành Tiền");
                tableDoanhThu.setModel(new DefaultTableModel(data_DoanhThu,header_DoanhThu));
                txtKetQua.setText(String.format("%f",dao_ThongKe.tinhTBDoanhThuThang(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()),Integer.parseInt(cbThangDoanhThu.getSelectedItem().toString()))));
                txtSLXeBan.setText(String.format("%d",dao_ThongKe.tinhTongBanThang(Integer.parseInt(txtNamTinhTongDoanhThu.getText().trim()),Integer.parseInt(cbThangDoanhThu.getSelectedItem().toString()))));
            }
        }
    }//GEN-LAST:event_btnTinhTBDoanhThuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKeNhapHang;
    private javax.swing.JButton btnTinhTBDoanhThu;
    private javax.swing.JButton btnTinhTongDoanhThu;
    private javax.swing.JComboBox<String> cbThangDoanhThu;
    private javax.swing.JComboBox<String> cbThangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableDoanhThu;
    private javax.swing.JTable tableTKNhapHang;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtNamNhap;
    private javax.swing.JTextField txtNamTinhTongDoanhThu;
    private javax.swing.JTextField txtSLXeBan;
    // End of variables declaration//GEN-END:variables
}
